In [1]:
import torch
import torch.distributions as dist
import matplotlib.pyplot as plt

In [4]:
X_1=torch.arange(4).view(-1,1)
X_2=torch.arange(3).view(1,-1)
X_1+X_2

tensor([[0, 1, 2],
        [1, 2, 3],
        [2, 3, 4],
        [3, 4, 5]])

In [5]:
B=X_1+X_2
B[0]

tensor([0, 1, 2])

In [11]:
X = torch.arange(10, dtype=float).reshape(5, 2)
diff=X[:,None,:]-X[None,:,:]
sq=diff**2
d_mat=torch.sqrt(sq.sum(-1))
d_mat

tensor([[ 0.0000,  2.8284,  5.6569,  8.4853, 11.3137],
        [ 2.8284,  0.0000,  2.8284,  5.6569,  8.4853],
        [ 5.6569,  2.8284,  0.0000,  2.8284,  5.6569],
        [ 8.4853,  5.6569,  2.8284,  0.0000,  2.8284],
        [11.3137,  8.4853,  5.6569,  2.8284,  0.0000]], dtype=torch.float64)

In [12]:
A = torch.arange(25).reshape(5, 5)

row_idx = torch.tensor([2, 3])
col_idx = torch.tensor([0, 1, 4])

# Use meshgrid to get all (row, col) pairs
R, C = torch.meshgrid(row_idx, col_idx, indexing='ij')  # shape [2, 3]

# Use fancy indexing
submatrix = A[R, C]

print(submatrix)


tensor([[10, 11, 14],
        [15, 16, 19]])


In [17]:
A = torch.arange(25).reshape(5, 5)

mask=(A%7==0)
print(mask)
print(A)

tensor([[ True, False, False, False, False],
        [False, False,  True, False, False],
        [False, False, False, False,  True],
        [False, False, False, False, False],
        [False,  True, False, False, False]])
tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])


In [18]:
A[mask]+=1
A

tensor([[ 1,  1,  2,  3,  4],
        [ 5,  6,  8,  8,  9],
        [10, 11, 12, 13, 15],
        [15, 16, 17, 18, 19],
        [20, 22, 22, 23, 24]])