In [1]:
import torch
import torch.distributions as dist
import matplotlib.pyplot as plt

In [5]:
M=torch.arange(0,9)
M=M.view(3,3)
M

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [6]:
M=torch.arange(0,9)
M=M.view(3,3).T
M

tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])

In [16]:
R=torch.arange(0,5)
repeated=R.repeat(3)
R, repeated

(tensor([0, 1, 2, 3, 4]),
 tensor([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4]))

In [20]:
R=torch.arange(0,5)
repeated=R.repeat(3,1)
R, repeated

(tensor([0, 1, 2, 3, 4]),
 tensor([[0, 1, 2, 3, 4],
         [0, 1, 2, 3, 4],
         [0, 1, 2, 3, 4]]))

In [28]:
n=4
main_diag=torch.ones(n)
lower_diag=torch.full((n-1,),-2.0)
upper_diag=torch.full((n-1,),-2.0)
A=(torch.diag(main_diag,diagonal=0)
   +torch.diag(lower_diag,diagonal=-1)
   +torch.diag(upper_diag, diagonal=1))

A

tensor([[ 1., -2.,  0.,  0.],
        [-2.,  1., -2.,  0.],
        [ 0., -2.,  1., -2.],
        [ 0.,  0., -2.,  1.]])

In [33]:
B=torch.arange(3)
B.unsqueeze(0).unsqueeze(0).unsqueeze(0)

tensor([[[[0, 1, 2]]]])

In [34]:
B = torch.arange(3)
B=B[None, None, None, :]
B

tensor([[[[0, 1, 2]]]])

In [35]:
B = torch.arange(3)
B=B.view(1,1,1,-1)
B

tensor([[[[0, 1, 2]]]])